[package]
name = "battle-arena"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.13.1"
lazy-init = "0.5.1"
thiserror = "1.0.40"
